{% set name = "pdal" %}
{% set version = "1.8.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/PDAL/PDAL/archive/{{ version }}.tar.gz
  sha256: ef3a32c06865383feac46fd7eb7491f034cad6b0b246b3c917271ae0c8f25b69
  patches:
    - hdf5.patch

build:
    number: 0

requirements:
  build:
    # - {{ compiler("c") }}
    # - {{ compiler("cxx") }}
    - cmake
    - ninja
    - python
    - numpy
    - pkg-config
  host:
    - python
    - numpy
    - libgdal {{ libgdal }}
    - geos
    - geotiff {{ geotiff }}
    # - postgresql 10.3.*
    - jsoncpp
    - eigen {{ eigen }}
    - sqlite
    # - laz-perf 1.2.*
    - nitro {{ nitro }}
    - hexer {{ hexer }}
    - laszip {{ laszip }}
    - curl
    - zlib
    - pcl {{ pcl }}
    - hdf5 {{ hdf5 }}
    - boost
    - vtk {{ vtk }}
    - tbb-devel
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - {{ pin_compatible('jsoncpp', max_pin='x.x.x') }}
    # - {{ pin_compatible('postgresql', max_pin='x.x') }}
    # - {{ pin_compatible('laz-perf', max_pin='x.x') }}
    - {{ pin_compatible('nitro', max_pin='x.x') }}
    - {{ pin_compatible('hexer', max_pin='x.x') }}
    - {{ pin_compatible('laszip', max_pin='x.x') }}
    - {{ pin_compatible('pcl', max_pin='x.x') }}
    - {{ pin_compatible('hdf5', max_pin='x.x.x') }}
    - libgdal {{ libgdal }}
    - geos
    - geotiff {{ geotiff }}
    - curl
    - zlib
    - boost
    - vtk {{ vtk }}
    - tbb-devel

test:
  commands:
    - pdal --version
    - pdal --drivers

about:
  home: https://www.pdal.io
  license: BSD 3-Clause
  summary: 'Point Data Abstraction Library (PDAL)'
  description: |
    Point cloud data processing.
  doc_url: https://www.pdal.io
  dev_url: https://github.com/pdal/pdal

extra:
  recipe-maintainers:
    - v-turin
